---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: juanpas.alpha.redhat.com
  description: ‘Juan Manuel Parrilla’
  labels: 
    - python_golang_lover
spec:
  group: alpha.redhat.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: juanpas
    singular: juanpa
    kind: Engineer
    shortNames:
      - Juanpa 
      - Parri
